name: aml-project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib
  - tqdm
  - pathlib
  - torchinfo
  - pip
  - pip:
    - pandas
    - numpy
    - torch
    - torchvision
    - jupyterlab
    - prettytable==3.5.0
